import type { ComponentType, ReactNode } from "react";
import {
  LuBadgeCheck,
  LuArchive,
  LuCircleHelp,
  LuCopy,
  LuDownload,
  LuFilter,
  LuGitBranchPlus,
  LuHistory,
  LuListFilter,
  LuMessageCircle,
  LuPanelsTopLeft,
  LuSettings2,
  LuShare2,
  LuTable,
  LuTicketCheck,
  LuTrash2,
  LuUsers,
} from "react-icons/lu";

export type ModalTone = "primary" | "success" | "danger" | "neutral";

export type ModalDefinition = {
  id: string;
  title: string;
  description?: string;
  icon?: ComponentType<{ className?: string }>;
  tone: ModalTone;
  submitLabel?: string;
  submittingLabel?: string;
  cancelLabel?: string;
  maxWidthClass?: string;
  confirmationKeyword?: string;
  confirmationAction?: string;
  validationMessages?: {
    wholeNumbers?: string;
    promptGreaterThanUsed?: string;
    studiesGreaterThanUsed?: string;
    questionsGreaterThanUsed?: string;
    changeAtLeastOneLimit?: string;
  };
};

export const modalDefinitions: Record<string, ModalDefinition> = {
  archiveStudy: {
    id: "archiveStudy",
    title: "Archive Study",
    tone: "primary",
    icon: LuArchive,
    submitLabel: "Archive",
    submittingLabel: "Archiving...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-2xl",
  },
  unarchiveStudy: {
    id: "unarchiveStudy",
    title: "Restore Study",
    tone: "success",
    icon: LuArchive,
    submitLabel: "Restore",
    submittingLabel: "Restoring...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-2xl",
  },
  copyStudy: {
    id: "copyStudy",
    title: "Copy Study",
    tone: "primary",
    icon: LuCopy,
    submitLabel: "Copy Study",
    submittingLabel: "Copying...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-2xl",
  },
  deleteStudy: {
    id: "deleteStudy",
    title: "Delete Study",
    tone: "danger",
    icon: LuTrash2,
    submitLabel: "Delete",
    submittingLabel: "Deleting...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-2xl",
  },
  copyQuestion: {
    id: "copyQuestion",
    title: "Copy Question",
    tone: "primary",
    icon: LuCopy,
    submitLabel: "Copy Question",
    submittingLabel: "Copying...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-2xl",
  },
  deleteQuestion: {
    id: "deleteQuestion",
    title: "Delete Question",
    tone: "danger",
    icon: LuTrash2,
    submitLabel: "Delete",
    submittingLabel: "Deleting...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-2xl",
  },
  activateSurvey: {
    id: "activateSurvey",
    title: "Activate Survey",
    tone: "success",
    icon: LuBadgeCheck,
    submitLabel: "Activate Survey",
    submittingLabel: "Activating...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-lg",
  },
  initiateSampleCollection: {
    id: "initiateSampleCollection",
    title: "Initiate Sample Collection",
    tone: "success",
    icon: LuUsers,
    submitLabel: "Initiate Sample Collection",
    submittingLabel: "Initiating...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-lg",
  },
  facebookLink: {
    id: "facebookLink",
    title: "Facebook Link",
    tone: "primary",
    icon: LuShare2,
    submitLabel: "Copy",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-4xl",
  },
  whatsappLink: {
    id: "whatsappLink",
    title: "WhatsApp Link",
    tone: "success",
    icon: LuMessageCircle,
    submitLabel: "Copy",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-4xl",
  },
  chooseSubgroup: {
    id: "chooseSubgroup",
    title: "Choose Subgroup",
    tone: "success",
    icon: LuListFilter,
    submitLabel: "Save",
    submittingLabel: "Saving...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-lg",
  },
  reportFilters: {
    id: "reportFilters",
    title: "Filters",
    tone: "primary",
    icon: LuFilter,
    submitLabel: "Save Filter List",
    submittingLabel: "Saving...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-lg",
  },
  downloadHistory: {
    id: "downloadHistory",
    title: "Download History",
    tone: "danger",
    icon: LuHistory,
    submitLabel: "Clear History",
    submittingLabel: "Clearing...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-2xl",
  },
  addBanner: {
    id: "addBanner",
    title: "Add Banner",
    tone: "primary",
    icon: LuPanelsTopLeft,
    submitLabel: "Design Banner",
    submittingLabel: "Creating...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-6xl",
  },
  copyBanner: {
    id: "copyBanner",
    title: "Copy Banner",
    tone: "primary",
    icon: LuCopy,
    submitLabel: "Copy Banner",
    submittingLabel: "Copying...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-2xl",
  },
  deleteBanner: {
    id: "deleteBanner",
    title: "Delete Banner",
    tone: "danger",
    icon: LuTrash2,
    submitLabel: "Delete",
    submittingLabel: "Deleting...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-2xl",
  },
  bannerSettings: {
    id: "bannerSettings",
    title: "Banner Settings",
    tone: "success",
    icon: LuSettings2,
    submitLabel: "Save Banner Settings",
    submittingLabel: "Saving...",
    cancelLabel: "Close",
    maxWidthClass: "max-w-6xl",
  },
  updateTable: {
    id: "updateTable",
    title: "Update Table",
    tone: "success",
    icon: LuTable,
    submitLabel: "Update Table",
    submittingLabel: "Updating...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-6xl",
  },
  logicEditor: {
    id: "logicEditor",
    title: "Edit or Add Logic",
    tone: "success",
    icon: LuGitBranchPlus,
    maxWidthClass: "max-w-5xl",
  },
  tableHistory: {
    id: "tableHistory",
    title: "Download History",
    tone: "danger",
    icon: LuDownload,
    submitLabel: "Clear History",
    submittingLabel: "Clearing...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-2xl",
  },
  addCustomTable: {
    id: "addCustomTable",
    title: "Add Custom Table",
    tone: "primary",
    icon: LuTable,
    submitLabel: "Add Custom Table",
    submittingLabel: "Creating...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-6xl",
  },
  addGroup: {
    id: "addGroup",
    title: "Set Group Name",
    tone: "primary",
    icon: LuGitBranchPlus,
    submitLabel: "Set Group Name",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-lg",
  },
  crosstabTable: {
    id: "crosstabTable",
    title: "Crosstab Table",
    tone: "neutral",
    icon: LuTable,
    submitLabel: "Close",
    cancelLabel: "Close",
    maxWidthClass: "max-w-5xl",
  },
  fullChartView: {
    id: "fullChartView",
    title: "Full Chart View",
    tone: "neutral",
    icon: LuPanelsTopLeft,
    submitLabel: "Close",
    cancelLabel: "Close",
    maxWidthClass: "max-w-5xl",
  },
  fullTableView: {
    id: "fullTableView",
    title: "Full Table View",
    tone: "neutral",
    icon: LuTable,
    submitLabel: "Close",
    cancelLabel: "Close",
    maxWidthClass: "max-w-5xl",
  },
  activateUser: {
    id: "activateUser",
    title: "Activate User",
    tone: "primary",
    icon: LuBadgeCheck,
    submitLabel: "Submit",
    submittingLabel: "Submitting...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-lg",
    confirmationKeyword: "confirm",
    confirmationAction: "activate",
  },
  deactivateUser: {
    id: "deactivateUser",
    title: "Deactivate User",
    tone: "primary",
    icon: LuBadgeCheck,
    submitLabel: "Submit",
    submittingLabel: "Submitting...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-lg",
    confirmationKeyword: "confirm",
    confirmationAction: "deactivate",
  },
  changeToPaidUser: {
    id: "changeToPaidUser",
    title: "Change To Premium User",
    tone: "primary",
    icon: LuUsers,
    submitLabel: "Submit",
    submittingLabel: "Submitting...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-lg",
    confirmationKeyword: "confirm",
    confirmationAction: "change to premium",
  },
  changeToFreeUser: {
    id: "changeToFreeUser",
    title: "Change To Free User",
    tone: "primary",
    icon: LuUsers,
    submitLabel: "Submit",
    submittingLabel: "Submitting...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-lg",
    confirmationKeyword: "confirm",
    confirmationAction: "change to free",
  },
  verifyUser: {
    id: "verifyUser",
    title: "Verify User",
    tone: "primary",
    icon: LuBadgeCheck,
    submitLabel: "Submit",
    submittingLabel: "Submitting...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-lg",
    confirmationKeyword: "confirm",
    confirmationAction: "verify",
  },
  removeUserVerification: {
    id: "removeUserVerification",
    title: "Remove Verification",
    tone: "primary",
    icon: LuBadgeCheck,
    submitLabel: "Submit",
    submittingLabel: "Submitting...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-lg",
    confirmationKeyword: "confirm",
    confirmationAction: "remove verification for",
  },
  updateUserSubscription: {
    id: "updateUserSubscription",
    title: "Update Subscription",
    description:
      "Enter the new limit. The entered value will become the updated limit.",
    tone: "primary",
    icon: LuSettings2,
    submitLabel: "Update Subscription",
    submittingLabel: "Submitting...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-2xl",
    validationMessages: {
      wholeNumbers: "Updated limits must be whole numbers.",
      promptGreaterThanUsed:
        "Updated prompt limit must be greater than prompts already used.",
      studiesGreaterThanUsed:
        "Updated study creation limit must be greater than studies already created.",
      questionsGreaterThanUsed:
        "Updated question generation limit must be greater than questions already generated.",
      changeAtLeastOneLimit: "Please change at least one subscription limit.",
    },
  },
  requestSupport: {
    id: "requestSupport",
    title: "Request for Assistance",
    description: "Get help from our research experts or technical support.",
    tone: "primary",
    icon: LuCircleHelp,
    submitLabel: "Request Assistance",
    submittingLabel: "Requesting...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-2xl",
  },
  supportTicketDetails: {
    id: "supportTicketDetails",
    title: "Support Ticket Details",
    tone: "primary",
    icon: LuTicketCheck,
    submitLabel: "Send Email",
    submittingLabel: "Sending...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-4xl",
  },
  subscriptionRequest: {
    id: "subscriptionRequest",
    title: "Subscription Request",
    tone: "primary",
    icon: LuMessageCircle,
    submitLabel: "Submit",
    submittingLabel: "Submitting...",
    cancelLabel: "Cancel",
    maxWidthClass: "max-w-xl",
  },
};

export const resolveModalText = (
  value: string | undefined,
  fallback: string
) => value ?? fallback;

export const renderModalIcon = (
  Icon: ComponentType<{ className?: string }> | undefined,
  className = "h-5 w-5"
): ReactNode => (Icon ? <Icon className={className} /> : null);
